repos:
- repo: https://github.com/psf/black
  rev: stable
  hooks:
    - id: black

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.761
  hooks:
    - id: mypy

- repo: https://github.com/pre-commit/mirrors-pylint
  rev: v2.4.4 # TODO: Update to v2.5.0 when available (for pyproject.toml)
  hooks:
    - id: pylint
      # We disable import-error since this is run outside poetry venv
      args: [--errors-only, --disable=E0401]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
    - id: trailing-whitespace
      exclude: ^tests/traces/.*
    - id: end-of-file-fixer
      exclude: ^tests/traces/.*
    - id: check-yaml
    - id: check-added-large-files
